### ISSUE TITLE
Versioning and AmCAT backwards compatibility issues

### ISSUE THREAD

**Issue by CJStuart** [amcat/amcat-query-js#2]
Currently we have no way of versioning in this repo.
AmCAT's bower.json refers to this repo as `git://github.com/amcat/amcat-query-js.git`, with no version information, which installs the latest version of the master branch. This breaks the query screen, since there's been some changes to the API in the last few versions. 

There are two things we can do:
- treat the master branch as a development branch, and split release branches off of this, like in the amcat repo. This is probably the easiest to implement right now, as there are already some commits on the master branch that would otherwise need to be moved.
- Create a development branch, and use the master branch as release branch. This is in my opinion the cleanest way, but it does require a bit of git magic. 

I suppose it's best to follow amcat's versioning, i.e. 3.4.1 for acmcat 3.4.1, etc. 

@martijnbastiaan, @vanatteveldt, do you have thoughts on this?

**Comment by martijnbastiaan** [comment]
I like the first proposal the most, as this allows us to maintain multiple releases at the same time. That, and I think it's conceptually the easiest way to go about it.

A third option would be to just tag along a [git submodule](https://git-scm.com/book/en/v2/Git-Tools-Submodules) in the main amcat repository
